require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListPagesController do

  # This should return the minimal set of attributes required to create a valid
  # ListPage. As you add validations to ListPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ListPagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all list_pages as @list_pages" do
      list_page = ListPage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:list_pages).should eq([list_page])
    end
  end

  describe "GET show" do
    it "assigns the requested list_page as @list_page" do
      list_page = ListPage.create! valid_attributes
      get :show, {:id => list_page.to_param}, valid_session
      assigns(:list_page).should eq(list_page)
    end
  end

  describe "GET new" do
    it "assigns a new list_page as @list_page" do
      get :new, {}, valid_session
      assigns(:list_page).should be_a_new(ListPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested list_page as @list_page" do
      list_page = ListPage.create! valid_attributes
      get :edit, {:id => list_page.to_param}, valid_session
      assigns(:list_page).should eq(list_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ListPage" do
        expect {
          post :create, {:list_page => valid_attributes}, valid_session
        }.to change(ListPage, :count).by(1)
      end

      it "assigns a newly created list_page as @list_page" do
        post :create, {:list_page => valid_attributes}, valid_session
        assigns(:list_page).should be_a(ListPage)
        assigns(:list_page).should be_persisted
      end

      it "redirects to the created list_page" do
        post :create, {:list_page => valid_attributes}, valid_session
        response.should redirect_to(ListPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved list_page as @list_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListPage.any_instance.stub(:save).and_return(false)
        post :create, {:list_page => {}}, valid_session
        assigns(:list_page).should be_a_new(ListPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListPage.any_instance.stub(:save).and_return(false)
        post :create, {:list_page => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested list_page" do
        list_page = ListPage.create! valid_attributes
        # Assuming there are no other list_pages in the database, this
        # specifies that the ListPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ListPage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => list_page.to_param, :list_page => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested list_page as @list_page" do
        list_page = ListPage.create! valid_attributes
        put :update, {:id => list_page.to_param, :list_page => valid_attributes}, valid_session
        assigns(:list_page).should eq(list_page)
      end

      it "redirects to the list_page" do
        list_page = ListPage.create! valid_attributes
        put :update, {:id => list_page.to_param, :list_page => valid_attributes}, valid_session
        response.should redirect_to(list_page)
      end
    end

    describe "with invalid params" do
      it "assigns the list_page as @list_page" do
        list_page = ListPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => list_page.to_param, :list_page => {}}, valid_session
        assigns(:list_page).should eq(list_page)
      end

      it "re-renders the 'edit' template" do
        list_page = ListPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => list_page.to_param, :list_page => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested list_page" do
      list_page = ListPage.create! valid_attributes
      expect {
        delete :destroy, {:id => list_page.to_param}, valid_session
      }.to change(ListPage, :count).by(-1)
    end

    it "redirects to the list_pages list" do
      list_page = ListPage.create! valid_attributes
      delete :destroy, {:id => list_page.to_param}, valid_session
      response.should redirect_to(list_pages_url)
    end
  end

end
