require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VillagesController do

  # This should return the minimal set of attributes required to create a valid
  # Village. As you add validations to Village, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VillagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all villages as @villages" do
      village = Village.create! valid_attributes
      get :index, {}, valid_session
      assigns(:villages).should eq([village])
    end
  end

  describe "GET show" do
    it "assigns the requested village as @village" do
      village = Village.create! valid_attributes
      get :show, {:id => village.to_param}, valid_session
      assigns(:village).should eq(village)
    end
  end

  describe "GET new" do
    it "assigns a new village as @village" do
      get :new, {}, valid_session
      assigns(:village).should be_a_new(Village)
    end
  end

  describe "GET edit" do
    it "assigns the requested village as @village" do
      village = Village.create! valid_attributes
      get :edit, {:id => village.to_param}, valid_session
      assigns(:village).should eq(village)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Village" do
        expect {
          post :create, {:village => valid_attributes}, valid_session
        }.to change(Village, :count).by(1)
      end

      it "assigns a newly created village as @village" do
        post :create, {:village => valid_attributes}, valid_session
        assigns(:village).should be_a(Village)
        assigns(:village).should be_persisted
      end

      it "redirects to the created village" do
        post :create, {:village => valid_attributes}, valid_session
        response.should redirect_to(Village.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved village as @village" do
        # Trigger the behavior that occurs when invalid params are submitted
        Village.any_instance.stub(:save).and_return(false)
        post :create, {:village => {}}, valid_session
        assigns(:village).should be_a_new(Village)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Village.any_instance.stub(:save).and_return(false)
        post :create, {:village => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested village" do
        village = Village.create! valid_attributes
        # Assuming there are no other villages in the database, this
        # specifies that the Village created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Village.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => village.to_param, :village => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested village as @village" do
        village = Village.create! valid_attributes
        put :update, {:id => village.to_param, :village => valid_attributes}, valid_session
        assigns(:village).should eq(village)
      end

      it "redirects to the village" do
        village = Village.create! valid_attributes
        put :update, {:id => village.to_param, :village => valid_attributes}, valid_session
        response.should redirect_to(village)
      end
    end

    describe "with invalid params" do
      it "assigns the village as @village" do
        village = Village.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Village.any_instance.stub(:save).and_return(false)
        put :update, {:id => village.to_param, :village => {}}, valid_session
        assigns(:village).should eq(village)
      end

      it "re-renders the 'edit' template" do
        village = Village.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Village.any_instance.stub(:save).and_return(false)
        put :update, {:id => village.to_param, :village => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested village" do
      village = Village.create! valid_attributes
      expect {
        delete :destroy, {:id => village.to_param}, valid_session
      }.to change(Village, :count).by(-1)
    end

    it "redirects to the villages list" do
      village = Village.create! valid_attributes
      delete :destroy, {:id => village.to_param}, valid_session
      response.should redirect_to(villages_url)
    end
  end

end
