source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  #gem 'coffee-rails', '~> 3.2.1'
  #css framework for using mixins
  gem 'compass-rails'
  gem 'bootstrap-sass'  

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

#CSV generator
gem 'csv_shaper'
#parsing
gem 'nokogiri'

#jquery 
gem 'jquery-rails'

#form simple generator --with bootstrap #or blueprint
#gem 'simple-form'

#photo, file asset manager
gem 'carrierwave'

#authentications
gem 'devise'

#test
group :development, :test do 
  gem 'rspec-rails'
  gem 'guard'
end 


# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
